(async()=>{
'use strict';
const $=s=>document.querySelector(s), canvas=$('#map'), ctx=canvas.getContext('2d'), earth=$('#earth'), detail=$('#detail');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data;try{const r=await fetch('fog-data.json');if(!r.ok)throw Error();data=await r.json()}catch{detail.textContent='Data unavailable. Reload the page to try again.';$('#loading').textContent='CONNECTION UNAVAILABLE';return}
const N=data.nodes,E=data.edges,B=Object.fromEntries(N.map(n=>[n.id,n])),located=n=>Number.isFinite(n.lat)&&Number.isFinite(n.lon)&&!n.approximate;
let W=0,H=0,dpr=1,yaw=20*Math.PI/180,pitch=25*Math.PI/180,zoom=1,selected=null,hovered=null,query='',filter='all',hits=[],scheduled=false,rotating=false;
const types={artist:'ARTIST / PRODUCER',label:'LABEL / COLLECTIVE',festival:'FESTIVAL',project:'RADIO / PROJECT'};
const match=n=>(filter==='all'||filter===n.type)&&(!query||[n.name,n.city,n.country,n.episode].join(' ').toLowerCase().includes(query));
const geo=()=>({cx:W*.51,cy:H*.49,R:Math.min(W*.47,H*.475)*zoom});
function project(n,alt=1){const a=n.lat*Math.PI/180,b=n.lon*Math.PI/180,X=Math.cos(a)*Math.sin(b),Y=Math.sin(a),Z=Math.cos(a)*Math.cos(b),xx=X*Math.cos(yaw)+Z*Math.sin(yaw),zz=-X*Math.sin(yaw)+Z*Math.cos(yaw),yy=Y*Math.cos(pitch)-zz*Math.sin(pitch),v=Y*Math.sin(pitch)+zz*Math.cos(pitch),{cx,cy,R}=geo();return{x:cx+xx*R*alt,y:cy-yy*R*alt,v}}
function requestDraw(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;draw()})}
let gl,program,texture,textureReady=false;
try{
gl=earth.getContext('webgl',{alpha:false,antialias:true});if(!gl)throw Error('WebGL');
const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};
program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,'attribute vec2 a;void main(){gl_Position=vec4(a,0.,1.);}'));
gl.attachShader(program,compile(gl.FRAGMENT_SHADER,`precision highp float;
uniform vec2 resolution;uniform vec2 center;uniform float radius;uniform float yaw;uniform float pitch;uniform sampler2D earthMap;
void main(){vec2 p=(gl_FragCoord.xy-center)/radius;float rr=dot(p,p);vec3 bg=vec3(.0078,.0157,.0235);if(rr>1.){float glow=exp(-(sqrt(rr)-1.)*43.)*.16;gl_FragColor=vec4(bg+vec3(.18,.40,.59)*glow,1.);return;}
float z=sqrt(1.-rr);float yy=p.y*cos(pitch)+z*sin(pitch);float zz=-p.y*sin(pitch)+z*cos(pitch);float xx=p.x*cos(yaw)-zz*sin(yaw);float zw=p.x*sin(yaw)+zz*cos(yaw);vec2 uv=vec2(.5+atan(xx,zw)/6.2831853,.5-asin(clamp(yy,-1.,1.))/3.14159265);vec3 t=texture2D(earthMap,uv).rgb;
// Preserve the original night palette, with a restrained lift to surface detail.
float light=max(0.,t.r-t.b*.72);
vec3 surface=pow(t,vec3(.90))*vec3(.48,.65,.76);
vec3 col=surface+vec3(1.5,.92,.27)*pow(light,.72)*2.45;
col*=.64+.36*pow(z,.35);
float rim=pow(1.-z,5.);col+=vec3(.07,.15,.22)*rim*.7;
gl_FragColor=vec4(col,1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Shader link');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
const img=new Image();img.onload=()=>{gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,img);textureReady=true;$('#loading').hidden=true;requestDraw()};img.onerror=()=>{$('#loading').textContent='Texture unavailable · the list and search remain accessible'};img.src='assets/earth-night.jpg';
}catch{$('#loading').textContent='3D globe unavailable in this browser. Explore the network using the list.'}
function drawEarth(){if(!gl||!textureReady)return;const {cx,cy,R}=geo();gl.viewport(0,0,earth.width,earth.height);gl.useProgram(program);gl.uniform2f(gl.getUniformLocation(program,'resolution'),earth.width,earth.height);gl.uniform2f(gl.getUniformLocation(program,'center'),cx*dpr,(H-cy)*dpr);gl.uniform1f(gl.getUniformLocation(program,'radius'),R*dpr);gl.uniform1f(gl.getUniformLocation(program,'yaw'),yaw);gl.uniform1f(gl.getUniformLocation(program,'pitch'),pitch);gl.drawArrays(gl.TRIANGLES,0,6)}
function draw(){if(!W||!H)return;drawEarth();ctx.clearRect(0,0,W,H);hits=[];const active=selected?new Set([selected,...E.filter(e=>e.source===selected||e.target===selected).flatMap(e=>[e.source,e.target])]):null;
// Only supplied relationships with both endpoints geographically available are drawn.
for(const e of E){const a=B[e.source],b=B[e.target];if(!a||!b||!located(a)||!located(b)||!match(a)||!match(b))continue;const A=project(a),C=project(b);if(A.v<0||C.v<0)continue;const relevant=!active||(active.has(a.id)&&active.has(b.id));ctx.strokeStyle=relevant?'rgba(168,205,235,.65)':'rgba(100,135,160,.18)';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.quadraticCurveTo((A.x+C.x)/2,(A.y+C.y)/2-Math.min(130,Math.hypot(A.x-C.x,A.y-C.y)*.35),C.x,C.y);ctx.stroke()}
const visible=N.filter(n=>located(n)&&match(n)).map(n=>({n,p:project(n)})).filter(o=>o.p.v>.03&&o.p.x>0&&o.p.x<W&&o.p.y>0&&o.p.y<H).sort((a,b)=>(b.n.id===selected)-(a.n.id===selected)||(a.n.type==='artist')-(b.n.type==='artist'));
const boxes=[];for(const {n,p} of visible){const gold=n.type!=='artist',color=gold?'#ffd17e':'#d9edff',fade=active&&!active.has(n.id);ctx.globalAlpha=fade?.43:1;ctx.shadowColor=color;ctx.shadowBlur=gold?18:12;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,n.id===selected?5:gold?3.8:2.8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(n.id===selected||n.type==='project'){ctx.strokeStyle='#d9b575';ctx.lineWidth=.75;ctx.beginPath();ctx.arc(p.x,p.y,10,0,Math.PI*2);ctx.stroke()}
hits.push({n,x:p.x,y:p.y});if(rotating||(n.id!==selected&&n.id!==hovered))continue;ctx.font='12px Arial';const name=n.name,width=ctx.measureText(name).width+14,height=34;const offsets=[[15,-14],[15,32],[-width-13,-14],[-width-13,38],[18,-60],[-width-15,76],[20,88]];let box;for(const [dx,dy] of offsets){const candidate={x:p.x+dx,y:p.y+dy,w:width,h:height};if(candidate.x<12||candidate.x+width>W-12||candidate.y<55||candidate.y+height>H-78)continue;if(!boxes.some(b=>candidate.x<b.x+b.w+8&&candidate.x+width+8>b.x&&candidate.y<b.y+b.h+4&&candidate.y+height+4>b.y)){box=candidate;break}}
if(box){boxes.push(box);ctx.strokeStyle='#71889b88';ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(box.x>p.x?box.x-4:box.x+box.w+3,box.y+8);ctx.stroke();ctx.shadowColor='#000';ctx.shadowBlur=5;ctx.fillStyle='#e0e7ef';ctx.fillText(name,box.x,box.y+11);ctx.font='8px Arial';ctx.fillStyle='#95a7b9';ctx.fillText(n.city.toUpperCase(),box.x,box.y+25);ctx.shadowBlur=0;hits.push({n,x:box.x+width/2,y:box.y+15,box})}}
ctx.globalAlpha=1;$('#coordinates').textContent=`LAT ${(pitch*180/Math.PI).toFixed(1)}°   LON ${(((-yaw*180/Math.PI+180)%360+360)%360-180).toFixed(1)}°`}
function size(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);earth.width=canvas.width;earth.height=canvas.height;ctx.setTransform(dpr,0,0,dpr,0,0);requestDraw()}new ResizeObserver(size).observe(canvas);
function row(n,subtitle){return `<button class="network-row" data-node="${esc(n.id)}"><i class="${n.type==='artist'?'white':'gold'}"></i><span>${esc(n.name)}<small>${esc(subtitle||n.city+' · '+n.country)}</small></span><span class="arrow">↗</span></button>`}
function overview(){detail.innerHTML=`<div class="eyebrow">MUSIC · PEOPLE · PLACES</div><h1 class="panel-title">A living musical<br>geography.</h1><p class="intro">An atlas of the people, labels and places connected through FOG.</p><div class="stats"><div><strong>71</strong><span>ENTRIES</span></div><div><strong>29</strong><span>CONNECTIONS</span></div></div><section class="section"><h2>EXPLORE THE PLACES</h2>${['fog','st','melifera','oslated','fhss'].map(id=>row(B[id])).join('')}</section><section class="section"><h2>GEOGRAPHIES IN PROGRESS</h2><p class="note">61 artists are available through search. Their provisional coordinates are not shown on the globe.</p><button class="network-row" id="pending"><span>Explore the artists<small>People, episodes and connections</small></span><span class="arrow">→</span></button></section><div class="badge">V0 places and connections · sources to verify</div><p class="note">The lights on Earth are part of the background map, not points in the FOG network.</p>`;$('#pending').onclick=()=>{filter='artist';$('#type').value=filter;openSearch();results();requestDraw()}}
function choose(n,focus=true){selected=n.id;if(located(n)){yaw=-n.lon*Math.PI/180;pitch=n.lat*Math.PI/180}const rel=E.filter(e=>e.source===n.id||e.target===n.id).map(e=>({e,n:B[e.source===n.id?e.target:e.source]})).filter(o=>o.n);detail.innerHTML=`<button class="back" id="close-detail" aria-label="Close details">×</button><h1 class="panel-title">${esc(n.name)}</h1><div class="eyebrow">${types[n.type]||esc(n.type)}</div><div class="location">⌖ &nbsp; ${esc(located(n)?n.city+', '+n.country:n.episode||'Location unknown')}</div><div class="badge">${located(n)?'V0 place · source to verify':'Location to verify'}</div><p class="intro">${located(n)?'Explore the connections in the FOG archive. The location supplied in V0 still needs confirmation from a source.':'This artist is part of the FOG archive. They are not shown on the globe until their location is confirmed.'}</p><section class="section"><h2>CONNECTED TO <span class="muted">/ ${rel.length}</span></h2>${rel.length?rel.map(o=>row(o.n,o.e.kind.replaceAll('_',' '))).join(''):'<p class="note">No connections recorded in V0.</p>'}</section>${n.episode?`<section class="section"><h2>FOG EPISODE</h2><p>${esc(n.episode)}</p><p class="note">An episode’s country does not establish an artist’s origin or residence.</p></section>`:''}<section class="section"><h2>DATA STATUS</h2><p class="note">Connections imported from V0, pending verification. No sources were included in the original file.</p></section>`;$('#close-detail').onclick=()=>{selected=null;overview();requestDraw()};$('#panel').scrollTop=0;closeSearch();requestDraw();if(focus&&innerWidth<=760)$('#panel').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
detail.addEventListener('click',e=>{const b=e.target.closest('[data-node]');if(b&&B[b.dataset.node])choose(B[b.dataset.node])});
function results(){const rows=N.filter(match);$('#count').textContent=`${rows.length} ${rows.length===1?'result':'results'} · ${rows.filter(located).length} ${rows.filter(located).length===1?'place':'places'} on the globe`;$('#results').innerHTML=rows.map(n=>`<button class="result ${located(n)?'':'pending'}" data-node="${esc(n.id)}">${esc(n.name)}<small>${esc(located(n)?n.city+' · V0 place to verify':(n.episode||'Artist')+' · location to verify')}</small></button>`).join('')||'<p class="note">No results. Try another name.</p>'}
$('#results').onclick=e=>{const b=e.target.closest('[data-node]');if(b)choose(B[b.dataset.node])};
function openSearch(){$('#explorer').hidden=false;$('#explore').setAttribute('aria-expanded','true');$('#search').focus()}
function closeSearch(){$('#explorer').hidden=true;$('#explore').setAttribute('aria-expanded','false')}
$('#explore').onclick=()=>$('#explorer').hidden?openSearch():closeSearch();$('#close-search').onclick=closeSearch;document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSearch();$('#explore').focus()}});
$('#search').oninput=e=>{query=e.target.value.trim().toLowerCase();results();requestDraw()};$('#type').onchange=e=>{filter=e.target.value;results();requestDraw()};
function reset(){yaw=20*Math.PI/180;pitch=25*Math.PI/180;zoom=1;selected=null;hovered=null;query='';filter='all';$('#search').value='';$('#type').value='all';overview();results();requestDraw()}
$('#reset').onclick=reset;$('#west').onclick=()=>{yaw+=.35;requestDraw()};$('#east').onclick=()=>{yaw-=.35;requestDraw()};$('#plus').onclick=()=>{zoom=Math.min(3.5,zoom*1.2);requestDraw()};$('#minus').onclick=()=>{zoom=Math.max(.7,zoom/1.2);requestDraw()};
const pointers=new Map();let origin,last,moved=false,pinch=0;
canvas.onpointerdown=e=>{hovered=null;requestDraw();pointers.set(e.pointerId,[e.clientX,e.clientY]);canvas.setPointerCapture(e.pointerId);origin=last=[e.clientX,e.clientY];moved=pointers.size>1;if(pointers.size>1){const [a,b]=[...pointers.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1])}};
canvas.onpointerleave=()=>{hovered=null;requestDraw()};
canvas.onpointermove=e=>{if(!pointers.has(e.pointerId)){const r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;const hit=hits.find(o=>!o.box&&Math.hypot(o.x-mx,o.y-my)<13);const next=hit?.n.id||null;if(next!==hovered){hovered=next;requestDraw()}return;}pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size>1){moved=true;const[a,b]=[...pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch>0)zoom=Math.max(.7,Math.min(3.5,zoom*d/pinch));pinch=d}else{if(Math.hypot(e.clientX-origin[0],e.clientY-origin[1])>5)moved=true;yaw+=(e.clientX-last[0])*.004;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-last[1])*.004))}rotating=moved;last=[e.clientX,e.clientY];requestDraw()};
canvas.onpointerup=e=>{if(!moved&&pointers.size===1){const r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;const hit=hits.find(o=>o.box?mx>=o.box.x&&mx<=o.box.x+o.box.w&&my>=o.box.y&&my<=o.box.y+o.box.h:Math.hypot(o.x-mx,o.y-my)<13);if(hit)choose(hit.n)}pointers.delete(e.pointerId);rotating=pointers.size>0;requestDraw();moved=true;pinch=0;if(pointers.size)origin=last=[...pointers.values()][0]};canvas.onpointercancel=e=>{pointers.delete(e.pointerId);rotating=pointers.size>0;requestDraw();moved=true;pinch=0};canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.7,Math.min(3.5,zoom*Math.exp(-e.deltaY*.001)));requestDraw()},{passive:false});
overview();results();size();
})();
